# basic image
FROM node:20

# set working dir
WORKDIR /usr/src/app

# we copy package files first to install dependencies
COPY MVC/package*.json ./

# now we install dependencies
RUN npm install

# we need to copy the rest of the application code
COPY MVC .

# the port our app runs on
EXPOSE 3000

# start the server
CMD ["node", "app.js"] 
